---
# tasks/main.yml for certbot
#
- name: Set certbot to "{{ wtd_certbot_state }}"
  package:
    name: "{{ wtd_certbot_packages }}"
    state: "{{ wtd_certbot_state }}"
  tags:
    - certbot

- name: Include "{{ wtd_certbot_create_method }}" Creation Tasks
  include_tasks: "create-{{ wtd_certbot_create_method }}.yml"
  with_items: "{{ wtd_certbot_create_domains }}"
  loop_control:
    loop_var: wtd_certbot_create_domain
  when:
    - wtd_certbot_create is defined
    - wtd_certbot_create_method is defined
    - wtd_certbot_create_domains is defined
  tags:
    - certbot

- name: Include "{{ wtd_certbot_renew_method }}" Renew Tasks
  include_tasks: "renew-{{ wtd_certbot_renew_method }}.yml"
  when:
    - wtd_certbot_renew is defined
    - wtd_certbot_renew_method is defined
  tags:
    - certbot
    - cron
